modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="druidcraft"
version="0.1"
displayName="Druidcraft"
logoFile=""
credits="Java, Forge, MCP, Minecraft, and the Mystic team for supporting me!"
authors="VulpTheHorseDog"
description='''
A druid-focused splice-of-life mod that's currently in very early alpha, if you'd even consider it at that point yet.

Regardless, I hope you enjoy the features as they're rolled out! :)
'''
[[dependencies.druidcraft]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
